// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2yYFXWNeDhrjbqWinx8PpgkHi1r_hUE',
    appId: '1:659410143816:web:0c3dfe6778c03109f8267d',
    messagingSenderId: '659410143816',
    projectId: 'shella1',
    authDomain: 'shella1.firebaseapp.com',
    databaseURL: 'https://shella1-default-rtdb.firebaseio.com',
    storageBucket: 'shella1.firebasestorage.app',
    measurementId: 'G-1NCSMFNKZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnrJzlof502Ry1fSLmJCjLCkMXv-Ebg8',
    appId: '1:659410143816:android:73ccbd3aeb8ab5b2f8267d',
    messagingSenderId: '659410143816',
    projectId: 'shella1',
    databaseURL: 'https://shella1-default-rtdb.firebaseio.com',
    storageBucket: 'shella1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioVSDEtk6UI7XXWIgIDrkwTXaJ6QQnHY',
    appId: '1:659410143816:ios:ca90c2ac14616528f8267d',
    messagingSenderId: '659410143816',
    projectId: 'shella1',
    databaseURL: 'https://shella1-default-rtdb.firebaseio.com',
    storageBucket: 'shella1.firebasestorage.app',
    iosBundleId: 'com.food.shala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDioVSDEtk6UI7XXWIgIDrkwTXaJ6QQnHY',
    appId: '1:659410143816:ios:dc2aa81e9a32cee6f8267d',
    messagingSenderId: '659410143816',
    projectId: 'shella1',
    databaseURL: 'https://shella1-default-rtdb.firebaseio.com',
    storageBucket: 'shella1.firebasestorage.app',
    iosBundleId: 'com.example.akram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK2yYFXWNeDhrjbqWinx8PpgkHi1r_hUE',
    appId: '1:659410143816:web:5ed74e7a969cac39f8267d',
    messagingSenderId: '659410143816',
    projectId: 'shella1',
    authDomain: 'shella1.firebaseapp.com',
    databaseURL: 'https://shella1-default-rtdb.firebaseio.com',
    storageBucket: 'shella1.firebasestorage.app',
    measurementId: 'G-KP6LWWDMGJ',
  );
}
